-
  name: running second playbook that deploys app and then deletes previous EC2 instance
  hosts: all
  become: yes
  become_method: sudo
  tasks:


    - name: Is this playbook2 working???????
      shell: ls






